import { ParameterDefinition, ParameterType } from '@/types/worldTypes';

export const lightingParams: ParameterDefinition[] = [
  {
    key: 'sunSize',
    label: 'Sun Size',
    description: 'Size of the sun',
    type: ParameterType.SLIDER,
    value: 2,
    min: 0,
    max: 20,
    step: 0.1,
    section: 'Sun',
  },
  {
    key: 'sunAngle',
    label: 'Sun Angle',
    description: 'Angle of the sun',
    type: ParameterType.SLIDER,
    value: 50,
    min: -90,
    max: 90,
    step: 1,
    section: 'Sun',
  },
  {
    key: 'sunDistance',
    label: 'Sun Distance',
    description: 'Distance of the sun',
    type: ParameterType.SLIDER,
    value: 25,
    min: 0,
    max: 1000,
    step: 1,
    section: 'Sun',
  },
  {
    key: 'sunLightColor',
    label: 'Sun Light Color',
    description: 'Color of the sunlight',
    type: ParameterType.COLOR,
    value: '#ffffdc',
    section: 'Sun',
  },
  {
    key: 'sunOuterColor',
    label: 'Sun Outer Color',
    description: 'Outer color of the sun',
    type: ParameterType.COLOR,
    value: '#ffbc05',
    section: 'Sun',
  },
  {
    key: 'sunInnerColor',
    label: 'Sun Inner Color',
    description: 'Inner color of the sun',
    type: ParameterType.COLOR,
    value: '#ff8800',
    section: 'Sun',
  },
  {
    key: 'sunEdgePower',
    label: 'Sun Edge Power',
    description: 'Edge power of the sun',
    type: ParameterType.SLIDER,
    value: 1.0,
    min: 0,
    max: 10,
    step: 0.01,
    section: 'Sun',
  },
  {
    key: 'sunIntensity',
    label: 'Sun Intensity',
    description: 'Brightness of the sun',
    type: ParameterType.SLIDER,
    value: 1.3,
    min: 0,
    max: 2,
    step: 0.1,
    section: 'Sun',
  },
  {
    key: 'castShadows',
    label: 'Cast Shadows',
    description: 'Enable shadow casting',
    type: ParameterType.BOOLEAN,
    value: true,
    section: 'Shadows',
  },
  {
    key: 'shadowQuality',
    label: 'Shadow Quality',
    description: 'Quality of shadow maps',
    type: ParameterType.SELECT,
    value: 'high',
    items: ['low', 'medium', 'high', 'ultra'],
    section: 'Shadows',
  },
  {
    key: 'shadowDistance',
    label: 'Shadow Distance',
    description: 'Size of the shadow camera frustum',
    type: ParameterType.SLIDER,
    value: 200,
    min: 50,
    max: 500,
    step: 10,
    section: 'Shadows',
  },
  {
    key: 'shadowRadius',
    label: 'Shadow Radius',
    description: 'Softness of shadow edges',
    type: ParameterType.SLIDER,
    value: 1.5,
    min: 0,
    max: 5,
    step: 0.1,
    section: 'Shadows',
  },
  {
    key: 'shadowBlurSamples',
    label: 'Shadow Blur Samples',
    description: 'Number of blur samples for shadows',
    type: ParameterType.SLIDER,
    value: 8,
    min: 1,
    max: 25,
    step: 1,
    section: 'Shadows',
  },
];
