import { ParameterDefinition, ParameterType } from '@/types/worldTypes';

export const lightingParams: ParameterDefinition[] = [
  {
    key: 'sunSize',
    label: 'Sun Size',
    description: 'Size of the sun sphere',
    type: ParameterType.SLIDER,
    value: 7,
    min: 1,
    max: 20,
    step: 0.5,
    section: 'Sun',
  },
  {
    key: 'sunAngle',
    label: 'Sun Angle',
    description: 'Angle of the sun in the sky',
    type: ParameterType.SLIDER,
    value: 50,
    min: 0,
    max: 360,
    step: 1,
    section: 'Sun',
  },
  {
    key: 'Test',
    label: 'Test',
    description: 'Angle of the sun in the sky',
    type: ParameterType.NUMBER,
    value: 50,
    min: 0,
    max: 360,
    step: 1,
    section: 'Sun',
  },
  {
    key: 'sunDistance',
    label: 'Sun Distance',
    description: 'Distance of the sun from center',
    type: ParameterType.SLIDER,
    value: 100,
    min: 50,
    max: 500,
    step: 10,
    section: 'Sun',
  },
  {
    key: 'sunIntensity',
    label: 'Sun Intensity',
    description: 'Brightness of the sun',
    type: ParameterType.SLIDER,
    value: 0.9,
    min: 0,
    max: 2,
    step: 0.1,
    section: 'Sun',
  },
  {
    key: 'sunLightColor',
    label: 'Light Color',
    description: 'Color of the sunlight',
    type: ParameterType.COLOR,
    value: '#ffffdc',
    section: 'Colors',
  },
  {
    key: 'sunOuterColor',
    label: 'Sun Outer Color',
    description: 'Outer glow color of the sun',
    type: ParameterType.COLOR,
    value: '#ffbc05',
    section: 'Colors',
  },
  {
    key: 'sunInnerColor',
    label: 'Sun Inner Color',
    description: 'Inner core color of the sun',
    type: ParameterType.COLOR,
    value: '#ff8800',
    section: 'Colors',
  },
  {
    key: 'sunEdgePower',
    label: 'Edge Power',
    description: 'Controls the edge glow falloff',
    type: ParameterType.SLIDER,
    value: 2.0,
    min: 0.1,
    max: 5.0,
    step: 0.1,
    section: 'Advanced',
  },
  {
    key: 'castShadows',
    label: 'Cast Shadows',
    description: 'Enable shadow casting',
    type: ParameterType.BOOLEAN,
    value: true,
    section: 'Advanced',
  },
  {
    key: 'shadowQuality',
    label: 'Shadow Quality',
    description: 'Quality of shadow maps',
    type: ParameterType.SELECT,
    value: 'high',
    items: ['low', 'medium', 'high', 'ultra'],
    section: 'Advanced',
  },
];
