import { ParameterDefinition, ParameterType } from '@/types/worldTypes';

export const skyboxParams: ParameterDefinition[] = [
  {
    key: 'resolution',
    label: 'Cube Texture Resolution',
    description: 'Resolution of each face of the cube texture (higher = better quality, slower)',
    type: ParameterType.SELECT,
    value: '2048',
    items: ['512', '1024', '2048', '4096'],
    section: 'Quality',
  },
  {
    key: 'backgroundEnable',
    label: 'Enable Background',
    description: 'Generate atmospheric background gradient',
    type: ParameterType.BOOLEAN,
    value: true,
    section: 'Background',
  },
  {
    key: 'backgroundColor',
    label: 'Background Color',
    description: 'Deep atmospheric blue color',
    type: ParameterType.COLOR,
    value: '#102e49',
    section: 'Background',
  },
  {
    key: 'midColor',
    label: 'Mid Color',
    description: 'Transition cyan-blue color',
    type: ParameterType.COLOR,
    value: '#113c67',
    section: 'Background',
  },
  {
    key: 'horizonColor',
    label: 'Horizon Color',
    description: 'Warm peachy horizon color',
    type: ParameterType.COLOR,
    value: '#6bb2e0',
    section: 'Background',
  },
  {
    key: 'noiseScale',
    label: 'Noise Scale',
    description: 'Base frequency for noise (higher = finer detail)',
    type: ParameterType.SLIDER,
    value: 5.0,
    min: 0.5,
    max: 10.0,
    step: 0.5,
    section: 'Background',
  },
  {
    key: 'noiseOctaves',
    label: 'Noise Octaves',
    description: 'FBM complexity (more = richer detail)',
    type: ParameterType.SLIDER,
    value: 6,
    min: 1,
    max: 8,
    step: 1,
    section: 'Background',
  },
  {
    key: 'posterizeSteps',
    label: 'Posterize Steps',
    description: 'Color quantization bands (lower = more stylized)',
    type: ParameterType.SLIDER,
    value: 14.0,
    min: 3.0,
    max: 100.0,
    step: 1.0,
    section: 'Background',
  },
  {
    key: 'gradientFalloffTop',
    label: 'Gradient Falloff Top',
    description: 'Controls top-to-mid transition',
    type: ParameterType.SLIDER,
    value: 1.3,
    min: 0.5,
    max: 3.0,
    step: 0.1,
    section: 'Background',
  },
  {
    key: 'gradientFalloffBottom',
    label: 'Gradient Falloff Bottom',
    description: 'Controls mid-to-horizon transition',
    type: ParameterType.SLIDER,
    value: 2.6,
    min: 0.5,
    max: 3.0,
    step: 0.1,
    section: 'Background',
  },
  {
    key: 'kuwaharaEnable',
    label: 'Enable Kuwahara Filter',
    description: 'Apply artistic edge-preserving smoothing filter',
    type: ParameterType.BOOLEAN,
    value: true,
    section: 'Kuwahara',
  },
  {
    key: 'filterRadius',
    label: 'Filter Radius',
    description: 'Brush stroke size (higher = more smoothing)',
    type: ParameterType.SLIDER,
    value: 7.0,
    min: 3.0,
    max: 20.0,
    step: 1.0,
    section: 'Kuwahara',
  },
  {
    key: 'sampleOffset',
    label: 'Sample Offset',
    description: 'Sampling density (lower = tighter sampling)',
    type: ParameterType.SLIDER,
    value: 0.0015,
    min: 0.0005,
    max: 0.01,
    step: 0.0005,
    section: 'Kuwahara',
  },
  {
    key: 'starsEnable',
    label: 'Enable Stars',
    description: 'Generate procedural star field',
    type: ParameterType.BOOLEAN,
    value: true,
    section: 'Stars',
  },
  {
    key: 'starsDensity',
    label: 'Star Density',
    description: 'Controls star field density (0 = very dense, 0.99 = very sparse)',
    type: ParameterType.SLIDER,
    value: 0.98,
    min: 0.0,
    max: 0.99,
    step: 0.01,
    section: 'Stars',
  },
  {
    key: 'starColorBase',
    label: 'Star Color (Base)',
    description: 'Middle range star color (default white)',
    type: ParameterType.COLOR,
    value: '#ffffff',
    section: 'Stars',
  },
  {
    key: 'starColorTint1',
    label: 'Star Color (Tint 1)',
    description: 'Cool blue tint for younger stars',
    type: ParameterType.COLOR,
    value: '#b3d9ff',
    section: 'Stars',
  },
  {
    key: 'starColorTint2',
    label: 'Star Color (Tint 2)',
    description: 'Warm orange/red tint for older stars',
    type: ParameterType.COLOR,
    value: '#ffd4a3',
    section: 'Stars',
  },
  {
    key: 'colorThreshold1',
    label: 'Color Threshold 1',
    description: 'Threshold between tint1 and base color',
    type: ParameterType.SLIDER,
    value: 0.3,
    min: 0.0,
    max: 1.0,
    step: 0.05,
    section: 'Stars',
  },
  {
    key: 'colorThreshold2',
    label: 'Color Threshold 2',
    description: 'Threshold between base and tint2 color',
    type: ParameterType.SLIDER,
    value: 0.7,
    min: 0.0,
    max: 1.0,
    step: 0.05,
    section: 'Stars',
  },
  {
    key: 'starBrightnessMin',
    label: 'Star Brightness Min',
    description: 'Minimum brightness for stars',
    type: ParameterType.SLIDER,
    value: 0.3,
    min: 0.0,
    max: 1.0,
    step: 0.05,
    section: 'Stars',
  },
  {
    key: 'starBrightnessMax',
    label: 'Star Brightness Max',
    description: 'Maximum brightness for stars',
    type: ParameterType.SLIDER,
    value: 0.8,
    min: 0.0,
    max: 2.0,
    step: 0.1,
    section: 'Stars',
  },
  {
    key: 'starSizeVariation',
    label: 'Star Size Variation',
    description: 'Controls star size randomness',
    type: ParameterType.SLIDER,
    value: 0.03,
    min: 0.005,
    max: 0.1,
    step: 0.005,
    section: 'Stars',
  },
];
