import { ParameterDefinition, ParameterType } from '@/types/worldTypes';

export const terrainParams: ParameterDefinition[] = [
  {
    key: 'seed',
    label: 'Seed',
    description: 'Master PRNG seed — controls all randomness in the generation pipeline',
    type: ParameterType.NUMBER,
    value: 12345,
    min: 0,
    max: 999999,
    step: 1,
    section: 'Terrain graph',
  },
  {
    key: 'size',
    label: 'Size',
    description: 'Terrain resolution — determines Poisson disk radius and resulting cell count',
    type: ParameterType.SELECT,
    value: 'Large',
    items: ['Tiny', 'Small', 'Medium', 'Large', 'Huge'],
    section: 'Terrain graph',
  },
  {
    key: 'island',
    label: 'Island',
    description: 'Influence of the distance falloff — higher values produce a more compact island',
    type: ParameterType.SLIDER,
    value: 0.7,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Island',
  },
  {
    key: 'roughness',
    label: 'Roughness',
    description: 'Influence of fBm noise — higher values produce a more jagged coastline',
    type: ParameterType.SLIDER,
    value: 0.7,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Island',
  },
  {
    key: 'ridgeCount',
    label: 'Ridge Count',
    description: 'Number of mountain spines',
    type: ParameterType.SLIDER,
    value: 2,
    min: 0,
    max: 8,
    step: 1,
    section: 'Ridges',
  },
  {
    key: 'ridgeLength',
    label: 'Ridge Length',
    description: 'Maximum walk steps per spine — controls how long a mountain range is',
    type: ParameterType.SLIDER,
    value: 40,
    min: 5,
    max: 120,
    step: 1,
    section: 'Ridges',
  },
  {
    key: 'ridgeWidth',
    label: 'Ridge Width',
    description: 'Lateral spread of each spine — 0 = thin blade, higher = broad range with spurs',
    type: ParameterType.SLIDER,
    value: 6,
    min: 0,
    max: 20,
    step: 1,
    section: 'Ridges',
  },
  {
    key: 'inlandOffset',
    label: 'Inland Offset',
    description:
      'Target depth contour as fraction of max coast distance — 0 = coastal arcs, 1 = central backbone',
    type: ParameterType.SLIDER,
    value: 0.55,
    min: 0.1,
    max: 1.0,
    step: 0.05,
    section: 'Ridges',
  },
  {
    key: 'elevationScale',
    label: 'Elevation Scale',
    description: 'Vertical scale of the terrain',
    type: ParameterType.SLIDER,
    value: 15,
    min: 0,
    max: 300,
    step: 1,
    section: 'Elevation',
  },
  {
    key: 'elevationRoughness',
    label: 'Elevation Roughness',
    description: 'FBM perturbation amplitude — higher values break up smooth slopes',
    type: ParameterType.SLIDER,
    value: 0.15,
    min: 0,
    max: 0.5,
    step: 0.01,
    section: 'Elevation',
  },
  {
    key: 'elevationNoise',
    label: 'Elevation Noise',
    description: 'FBM frequency for the roughness layer',
    type: ParameterType.SLIDER,
    value: 1.5,
    min: 0.1,
    max: 8,
    step: 0.1,
    section: 'Elevation',
  },
  {
    key: 'debugMode',
    label: 'Debug Mode',
    description: 'Visualization layer — switch to inspect each generation step',
    type: ParameterType.SELECT,
    value: 'elevation',
    items: ['cell', 'island', 'ridges', 'elevation'],
    section: 'Debug',
  },
];
